### ISSUE TITLE
Add support for KTX image format

### ISSUE THREAD

**Issue by netroy** [image-size/image-size#124]
it was pointed to me that adding support for [KTX](https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/#1) would be simple.
So, I'm creating this ticket to track progress.

**Comment by netroy** [comment]
@ZaneHannanAU nice :)
I've been meaning to convert the code to typescript as well.
would you like to send a PR after that?

**Comment by ZaneHannanAU** [comment]
I would; the main issue is that it would break a lot.

Also I've done zero actual testing so ... yeah.
