### ISSUE TITLE
Add support for MPEG-H/HEIF image format

### ISSUE THREAD

**Issue by netroy** [image-size/image-size#125]
[More information](https://mpeg.chiariglione.org/standards/mpeg-4/iso-base-media-file-format)

**Comment by cachila** [comment]
Really looking forward to this enhancement.

Do you have an ETA?

**Comment by netroy** [comment]
a large chunk of this work is investigating the HEIF container format & figuring out how to parse out the relevant "boxes". If you can find some definitive & concise documentation, it might help getting this done quicker.
What I'd need it, is clear docs on how these images are structured byte-by-byte, to be able to create a first version of the parser.

But, considering my current workload, I can't really give an ETA here.

**Comment by netroy** [comment]
@phal0r the key feature of this module is that it doesn't pull in any heavy dependencies.
That said, I've tried using libheif directly, and while it worked for heif/heic files, it failed for most avif files for me.

If someone were to implement heif container decoding without any external dependencies, I'd be more than happy to help.
I just haven't had the time (or focus) to do that myself.

**Comment by phal0r** [comment]
@netroy I re-read the snippet I linked and I think detecting heic/heif images takes a raw buffer and treats the header as fixed size and just slices a fixed number of bytes at a fixed position to detect the format. it does not use libheif for detection.

**Comment by netroy** [comment]
@phal0r yeah. 
we've already had a valid detection code for 3 years now (not in `main` yet). 
what we're blocked by is everything else. 

![image](https://user-images.githubusercontent.com/196144/160797436-aae3c5d0-5295-44e5-b5b6-fd6dde57f2fe.png)

**Comment by phal0r** [comment]
ok, right. by `everything else` you mean detection of the dimensions. I was only focussing on the type :D

**Comment by phal0r** [comment]
Thanks for the suggestion. Looks like a pretty cool lib, but I need the image dimensions aswell.

**Comment by donmccurdy** [comment]
I wrote up a short bit of code to probe .avif and .heic files for their size recently, available here:

https://github.com/donmccurdy/glTF-Transform/blob/8062f29382b93877485273cd5d02c4279ef97468/packages/extensions/src/ext-texture-avif/texture-avif.ts#L19-L51

The main limitation is that it doesn't handle image sequences or orientation metadata, as I didn't need that for my use cases. If that's OK, I'm happy to do a PR here. My work referenced a more complete (but also more verbose) implementation found [here](https://github.com/nodeca/probe-image-size/blob/master/lib/parse_sync/avif.js).

**Comment by netroy** [comment]
released in v1.1.0
