### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by budgidiere** [image-size/image-size#169]
I get Module not found: `Can't resolve 'fs' in '(wheremycodeis)\node_modules\image-size\types'` whenever I try to use image-size. I have tried `npm i fs --save` but that did not work.

**Comment by AlbertoFardin** [comment]
same issue

**Comment by netroy** [comment]
@budgidiere can you share more information? 
* where was this code running?
* what file (or buffer) you received this error on?

**Comment by netroy** [comment]
@budgidiere ping

@AlbertoFardin do you see this error in a frontend application? are you using babel, or webpack?

**Comment by budgidiere** [comment]
@netroy I just fixed it I had to add 
node: {
  fs: 'empty'
}
To my webpack config.
