### ISSUE TITLE
The value of "offset" is out of range. It must be >= 0 and <= 4. Received 14

### ISSUE THREAD

**Issue by Dog-leash** [image-size/image-size#181]
hello, when i use image-size to get this image's width and height 'http://pgdt.gtimg.cn/gdt/0/EAAjrNfAMgAIRAAAOAQBcGwk_AZQKm-I8.jpg/0'.
i always get the same error. May i ask the error is caused by the image(is it bad?) or the image-size library? 
![error](https://user-images.githubusercontent.com/15243547/56404180-cc60f200-6297-11e9-843d-80d83a614eae.png)
Thanks u~

**Comment by netroy** [comment]
This looks like a regression from #150.
Thanks for opening the PR

**Comment by netroy** [comment]
fix published in `v0.7.4`
