### ISSUE TITLE
Update docs for default import

### ISSUE THREAD

**Issue by antoinerousseau** [image-size/image-size#225]
When first reading the doc, I did
```js
import imageSize from 'image-size'
```
But my IDE complained that there isn't any default export.
In fact, in `index.js` there is a line that makes it work:
```js
module.exports = exports = imageSize; // backwards compatibility
```
But it's a compatibility code and it's not referenced in the typings, so the doc should be updated accordingly like this:
```js
import {imageSize} from 'image-size'
```
Or with `require`:
```js
const {imageSize} = require('image-size')
```

**Comment by netroy** [comment]
The module is now exported to work in all three ways.
Thanks for reporting this. cheers.

**Comment by hyoretsu** [comment]
But the `promisify` weird thing isn't demonstrated using `import`.
