### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by kevinhimawan** [image-size/image-size#240]
Hello i am using synchronous method because i only can use URL then convert to BUFFER

However sometimes get weird error when process multiple images (eg. above 50 images)
<img width="629" alt="Screenshot 2019-11-01 at 8 16 18 AM" src="https://user-images.githubusercontent.com/33747932/67995989-e8e6d980-fc7f-11e9-9af9-059626a0c2d7.png">

This is my helper function:
<img width="405" alt="Screenshot 2019-11-01 at 8 15 48 AM" src="https://user-images.githubusercontent.com/33747932/67995981-d8cefa00-fc7f-11e9-87f6-710702786362.png">

my question are
1. How to process multiple images (when i have to loop multiple images and get image's size)
2. How to process when my server have a huge traffic to do this get image's size API?

**Comment by kevinhimawan** [comment]
`activities.reduce((accPromise, activity, index) => {
      return accPromise.then(async () => {
        await timeOut()
        let files = await Promise.all(activity.files.map(async file => {
          let result;
          try {
            result = await decodeSizeImageURL(file.url)
            !result ? result = { width: 0, height: 0 } : null
          } catch (e) {

            result = { width: 0, height: 0 }
          }
          return { 
            ...file, 
            width: result.width,
            height: result.height,
            ratio: result.width !== 0 ? (result.width / result.height) : 0
          }
        }))
        await Activity.updateOne(
          { _id: activity._id },
          { $set: { files }}
        )
        console.log('Done '+ index)
      })
    }, Promise.resolve())`

If i am using timeOut let say 3s for every loop, then it would be fine. But this method is not sustainable

**Comment by netroy** [comment]
@kevinhimawan the issue seems unrelated to this library. 
from the looks of it, it seems your dns resolution is timing out, possibly because the dns resolver is overwhelmed by the number of dns requests.

depending on where this code is running, it might make sense to run a local dns resolver like dnsmasq.

I'll close this ticket, because it's not relevant to this repo.
But, if you need more info on how to setup a local resolver, please let me know. Maybe I can help you over email.

**Comment by netroy** [comment]
Also, can you please check if the urls are always `https`, & never `http`

**Comment by kevinhimawan** [comment]
Hello thank you for your reply. I am using Google Cloud Bucket for storing
our images

Do you have any idea how to handle this?

Thank you

**Comment by netroy** [comment]
Hey, I meant to ask, in what environment is the nodejs code running?
