### ISSUE TITLE
HEIC Files

### ISSUE THREAD

**Issue by emmtte** [image-size/image-size#247]
Do you know if this repo support HEIC photo file

**Comment by netroy** [comment]
Hey @ManuCart, 
HEIC containers aren't supported yet.
as there hasn't been any demand for it so far.

If you have some time to add support, give it a shot. 
If not, I can try sometime next week to start with it. 

Cheers :)

**Comment by ManuCart** [comment]
I don't have the background to do this.
I will wait. Thanks for your help

**Comment by netroy** [comment]
duplicate of #125

**Comment by netroy** [comment]
released in v1.1.0
