### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS while parsing png (windows, linux subsystem)

### ISSUE THREAD

**Issue by maxhawkins** [image-size/image-size#260]
Running `imageSize` on the attached png throws an out of bounds exeption while using Linux on Windows. The package works fine for other png and jpg files. The package works fine parsing the same file on macOS.

Error:
```
internal/buffer.js:70
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:70:11)
    at Buffer.readUInt16LE (internal/buffer.js:229:5)
    at Object.validate (/<redacted>/node_modules/image-size/dist/types/cur.js:7:20)
    at finder (/<redacted>/node_modules/image-size/dist/detector.js:26:55)
    at Array.find (<anonymous>)
    at Object.detector (/<redacted>/node_modules/image-size/dist/detector.js:27:17)
    at lookup (/<redacted>/node_modules/image-size/dist/index.js:32:29)
    at imageSize (/<redacted>/node_modules/image-size/dist/index.js:102:16)
    at <redacted> (/<redacted>/makeManifest.js:20:7)
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```

Image file:
![handset_icon@3x](https://user-images.githubusercontent.com/28565/70665726-0c5b5780-1c22-11ea-8829-d4f37d6eacae.png)

System:
**OS:** Ubuntu 18.04 bionic [Ubuntu on Windows 10]
**Kernel:** x86_64 Linux 4.4.0-18362-Microsoft
**CPU:** Intel Core i7-8565U @ 8x 2.001Ghz
**image-size version**: 0.8.3 (npm)

**Comment by netroy** [comment]
@maxhawkins 
This looks like it could be an issue in nodejs on WSL.
Since I don't have access to such a setup,  would it be possible for you to debug this a bit for me?

I pushed a branch with some `console.log`, that might be able to help me confirm my suspicion that somehow reading from buffers is either destructive, or is moving an internal offset/pointer.

If possible, can you please make these changes in `detector.js` in your  node_modules, & test it again?
here are the changes https://github.com/image-size/image-size/compare/debug?expand=1

**Comment by jcald1** [comment]
@netroy , I'm also getting your same error on Linux.  I tried your branch:

```
yarn remove image-size
yarn add https://github.com/image-size/image-size#debug
```

but I get the following error:

`Error: Cannot find module '/var/task/node_modules/image-size/dist/index.js'. Please verify that the package.json has a valid "main" entry`

**Comment by netroy** [comment]
@jcald1 can you please go into the `/var/task/node_modules/image-size` folder, & run `yarn && tsc`?
Since this issue was created, the code has been converted to typescript. This module needs a precompilation step now.
after compiling the module, can you please try again?
if you don't manage to get it working, please let me know. I'll create an alpha release for testing.

**Comment by netroy** [comment]
@jcald1 also, would it be possible to share the image that's causing this issue? it might help me reproduce the issue.

**Comment by jcald1** [comment]
@netroy ,

I compiled it and generated the following logs:

```
2020-02-06T01:21:22.363Z	1493b1ed-58bc-16fe-f353-b56cb1071e6e	INFO	Initial buffer length 524288
2020-02-06T01:21:22.364Z	1493b1ed-58bc-16fe-f353-b56cb1071e6e	INFO	Quick lookup for jpg. Buffer length 524288
2020-02-06T01:21:22.364Z	1493b1ed-58bc-16fe-f353-b56cb1071e6e	INFO	3******** { height: 11600, orientation: 1, width: 11600, type: 'jpg' } /tmp/123458/variants/OWL+1.jpg

```

You can copy the image from here:

```
https://media-upload-v1-dev-use1.s3.amazonaws.com/integration-tests/OWL+1.jpg
```

**Comment by netroy** [comment]
@jcald1 that looks like the library worked for you as expected.
are you able to reproduce the error `ERR_BUFFER_OUT_OF_BOUNDS` for png files?

**Comment by jcald1** [comment]
@netroy , I still got the error on that jpg file.

**Comment by netroy** [comment]
@jcald1 I'm unable to reproduce this on Linux
```
$ bin/image-size.js ../OWL+1.jpg
11600x11600 - ../OWL+1.jpg (jpg)
```

I have access to a windows machine with WSL now. will try to reproduce this there.

**Comment by amitm02** [comment]
I have the same issue on large images under docker container

**Comment by netroy** [comment]
unable to reproduce these

**Comment by tiavina-mika** [comment]
I have the same issue when running multiple request with large image input at the same time.

My app is hosted to Google Cloud Plateform and the file saved to Google Storage

**Comment by netroy** [comment]
@tiavina-mika can you share an image with us, that I could reproduce the issue with?
Also, can you share with us what version of the library you are using?

**Comment by tiavina-mika** [comment]
> @tiavina-mika can you share an image with us, that I could reproduce the issue with?
> Also, can you share with us what version of the library you are using?


https://storage.googleapis.com/montage-preprod-xxxxxx/montage-preprod-xxxxxx_favp88pkifn9.jpeg

**Comment by netroy** [comment]
@tiavina-mika 
I'm unable to reproduce this on the latest release of the library. I get `2500x1875` as expected.
Can you share more information about the environment you are seeing this error on?

**Comment by wouterlemcke** [comment]
We're running on AWS ec2's (Node.js 14 running on 64bit Amazon Linux 2/5.5.3).
We use this lib to calculate the dimensions of images uploaded by users of our app, so it's a bit hard to give you some example images. It's really hard to reproduce this issues we noticed (we were not able to yet), but from our logs we see it happening quite often.

**Comment by netroy** [comment]
@wouterlemcke can you please also share the exact version of node.js and the exact version of this lib that you are using ?

**Comment by wouterlemcke** [comment]
The images are posted through forms and while processing stored in temp storage.
`const dimensions = sizeOf(fs.readFileSync(path))`

Where the path is the path to the file in temp storage. The files are also uploaded to s3 and this never fails and never results in corrupted images, so I'm pretty sure there's no issue with the files itself. 

In our case it's mostly used for profile images, so I cannot easily share a file that's results in an error, once I find one that does not contain personal info I will share it.

**Comment by wouterlemcke** [comment]
We're upgrading to Node 16. We hope this will also magically solve this issue. I will keep you posted

**Comment by wouterlemcke** [comment]
Unfortunately the Node upgrade did not solve the issue..
