### ISSUE TITLE
latest version warnings

### ISSUE THREAD

**Issue by emps** [image-size/image-size#261]
using latest version throwing errs

ExperimentalWarning: The fs.promises API is experimental

please change it using util.promisify on fs dont use experimentals for production thanks

**Comment by tmathern** [comment]
This depends on the node version you use. 
The experimental warning for fs.promises was removed in https://github.com/nodejs/node/pull/26581, which is v11.4.0 of node. If you can update your node version, you can move to a higher one. Otherwise, util.promisify would be the only way to go.

**Comment by bluenote10** [comment]
I'm running version 11.6.0 and get the warning.

**Comment by kPepis** [comment]
> I'm running version 11.6.0 and get the warning.

He missed a '1'. It's v11.14.0

**Comment by netroy** [comment]
as `fs.promises` is stable now, I'm closing this.
