### ISSUE TITLE
unsupported file type: undefined (file: undefined)

### ISSUE THREAD

**Issue by guillaumearm** [image-size/image-size#280]
Hi.

Yes, this error again 🤓  

I used the documentation example with this (working) url: https://app-cdn.clickup.com/assets/favicons/apple-touch-icon.png

Something wrong with this png image ?

```ts
var url = require('url');
var http = require('http');

var sizeOf = require('image-size');

var imgUrl = 'https://app-cdn.clickup.com/assets/favicons/apple-touch-icon.png';
var options = url.parse(imgUrl);

http.get(options, function (response) {
  var chunks = [];
  response.on('data', function (chunk) {
    chunks.push(chunk);
  }).on('end', function() {
    var buffer = Buffer.concat(chunks);
    console.log(sizeOf(buffer));
  });
});
```

Tested with node v12.9.1 and `image-size@0.8.3`

**Comment by agrotech-cowboy** [comment]
Hi @guillaumearm,

Did you manage to solve? Same problem for any image of type `.png` 😞

**Comment by akanshgulati** [comment]
@netroy Please help here. Even #241 Is related to this only. I think its coming after 12.14.0 version of node.

**Comment by netroy** [comment]
@guillaumearm looks like the image you mentioned is being served gzipped. this library does not handle decompressing gzip files.
you can either handle doing decompression yourself with `zlib`, or use a library that handles these things transparently.

Here is an example using `axios`:

```javascript
const axios = require('axios')
const sizeOf = require('image-size')

axios.get('https://app-cdn.clickup.com/assets/favicons/apple-touch-icon.png', {
  responseType: 'arraybuffer'
}).then(response => {
  console.log(sizeOf(response.data))
})
```

**Comment by netroy** [comment]
@akanshgulati #241 is a completely different issue. Can you try what I've suggested in the post above?
