### ISSUE TITLE
It works, but "fs" dependancy even after installing "fs"

### ISSUE THREAD

**Issue by Guebbit** [image-size/image-size#289]
Hello I'm using nuxt 2.11.0 and I can't manage to use this module.
First, I had this error:

![error](https://user-images.githubusercontent.com/12038511/76703865-3b77de00-66d5-11ea-8f3a-855fbcd1114a.png)

After installing the module, it continues like this:

![error2](https://user-images.githubusercontent.com/12038511/76704118-1be1b500-66d7-11ea-9b0d-e269d45f0b2f.png)

Following some instructions, I tryed to make `node: { fs: 'empty' }`, but I had no luck:

![error3](https://user-images.githubusercontent.com/12038511/76704183-682cf500-66d7-11ea-81fe-97c7b482acb6.png)

I just needed the plugin to dynamically retrieve the width of the images and compile a srcset with the images I already created and optimized, but I can't pull this off...

**Comment by SheetJSDev** [comment]
This is unavoidable as currently structured, the fix requires a deep change.

It looks like the TIFF parser needs to read some part near the end of the file, and the file utilities [do not necessarily read the entire file](https://github.com/image-size/image-size/blob/master/lib/index.ts#L520).  In the interest of expediency, the original authors just added `fs` as a dependency to TIFF.

The necessary "deep change" is obvious: somehow the file libraries must be able to communicate that they need the entire file and not just a partial buffer.

**Comment by JonathanTreffler** [comment]
Is it possible to disable tiff support somehow ? These compilation errors mess up nuxt.js and it does not even attempt to compile the rest of my project.
Since i don't see a setting that allows me to disable tiff support, do i need to fork and remove tiff ?

**Comment by netroy** [comment]
It's now possible to [disable file-system reads](https://github.com/image-size/image-size#disabling-all-file-system-reads), or to [disable certain image types](https://github.com/image-size/image-size#disabling-certain-image-types), as of version `0.9.4`.

But, these changes won't fix the issue with nuxj.js or any other tool that executes `image-size` in the browser, unless the code calling this library creates a `Buffer` like object, and passes that the input.

If nuxtjs does rendering on both the client-side and the server-side (for SSR), then I'd recommend putting a check in your code to not call this library when running in the browser. Perhaps a `typeof window === 'undefined'` should suffice.
