### ISSUE TITLE
add --json flag for CLI

### ISSUE THREAD

**Issue by joelnet** [image-size/image-size#304]
Add `--json` support for cli tooling.

```shell
image-size --json image1.png image2/png image3.png
```

output:

```json
{
  "image1.png": {
    "height": 1080,
    "width": 1920,
    "type": "png"
  },
  "image2.png": {
    "height": 1080,
    "width": 1920,
    "type": "png"
  },
  "image3.png": {
    "height": 1080,
    "width": 1920,
    "type": "png"
  }
}
```

Pull Request --> #303

**Comment by netroy** [comment]
Thanks for doing this. 
But sorry, I don't want to maintain features for every single user. 

Don't get me wrong. Something like this can be very helpful as it's own package.
But, it doesn't need to be included in this repo.

PR: Please talk to project maintainers before creating feature PRs, as not wanting to merge someone's hard work leaves both of us disappointed.
I hope you understand.

**Comment by joelnet** [comment]
Totally understand. Cheers 🍻
