### ISSUE TITLE
(node:19430) Warning: Closing file descriptor 63 on garbage collection

### ISSUE THREAD

**Issue by geogeim** [image-size/image-size#342]
I'm running a long lived process that periodically downloads some images from a cdn. Sometimes the cdn is flaky and truncates the responses or returns empty files. Then i get the following errors 

```
message:'Empty file'
name:'Error'
stack:'Error: Empty file\n    at /home/git/idwn/node_modules/image-size/dist/index.js:54:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/git/idwn/node_modules/image-size/dist/index.js:5:58)'

...
(node:19430) Warning: Closing file descriptor 63 on garbage collection
```

I think the module is leaking file handles

**Comment by netroy** [comment]
@geogeim thanks for pointing this out. 
This has been fixed in https://github.com/image-size/image-size/commit/62f48f6e5674b088ebe7b3d1829ab2d84480005f & released as `0.9.2`
