### ISSUE TITLE
Support avif format

### ISSUE THREAD

**Issue by PiQx** [image-size/image-size#350]
hello. Tell me whether support for avif format will be added?

**Comment by netroy** [comment]
@PiQx this is a duplicate of https://github.com/image-size/image-size/issues/125
as I've pointed out in [a comment on that issue](https://github.com/image-size/image-size/issues/125#issuecomment-724731127), I currently do not have the time to investigate the HEIF container format. 
If you (or someone else) can do that research for me, and provide me with some easy to understand documentation, I can get the code working as soon as I can.

**Comment by netroy** [comment]
released in v1.1.0
