### ISSUE TITLE
Gets width and height mixed up on rotated camera photos

### ISSUE THREAD

**Issue by richard-stern** [image-size/image-size#352]
When a photo is taken with a rotated camera, some cameras store the fact that the they were rotated in the image header rather than swapping the width and height. this library doesn't respect that flag.

This means you can have an image that displays as 1000x4000 and windows says it's 1000x4000 but this library reports it as 4000x1000.

I found that simply opening the image and re-saving it from photoshop fixes the problem but this isn't really a solution. This library should respect that flag and swap the width and height if it indicates that the image is rotated.

Here is an image that causes the issue so you can try it for yourself and see that it gets the dimensions wrong:
https://cdn.discordapp.com/attachments/313901819287830529/791617802434773052/20201224_214314.jpg

**Comment by netroy** [comment]
@richard-stern for jpegs, this library [returns an extra `orientation` field](https://github.com/image-size/image-size/blob/master/lib/types/interface.ts#L4), if it is defined in the EXIF metadata (which is almost always).
Looks like we never managed to get around to documenting it.

Let me know if you need any more information.
Also, if you have any suggestions for the documentation, contributions are always welcome.
Cheers
