### ISSUE TITLE
ES6 support? 

### ISSUE THREAD

**Issue by geoidesic** [image-size/image-size#365]
Can you include examples in the README of how to use this with the `import` ES6 modules syntax?
When I tried it I get this error:
```
TypeError: Cannot read property 'call' of undefined
    at new Queue (http://localhost:3000/node_modules/.vite/image-size.js?v=708f89e6:98:20)
    at node_modules/image-size/dist/index.js (http://localhost:3000/node_modules/.vite/image-size.js?v=708f89e6:1189:17)
    at __require (http://localhost:3000/node_modules/.vite/chunk-AXBC2VTT.js?v=708f89e6:6:44)
    at http://localhost:3000/node_modules/.vite/image-size.js?v=708f89e6:1273:26
```

**Comment by netroy** [comment]
this already supports ES6 (for over 2 years now).
Just create a `test.mjs` file with 
```
import imageSize from 'image-size'
imageSize("/path/to/image/file", (err, size) => console.log(err, size))
```
and it worked.

tried with typescript, and that worked as well. 

please make sure that you are using the latest version of the module, and this is not an issue with vite itself.

**Comment by netroy** [comment]
@geoidesic does this answer this question?

**Comment by geoidesic** [comment]
No, it doesn't. I can't get this library to work. I tried via Yarn and with the example you show above and I get a different error:
```
500
The requested module '/node_modules/image-size/dist/index.js' does not provide an export named 'default'

SyntaxError: The requested module '/node_modules/image-size/dist/index.js' does not provide an export named 'default'
```

**Comment by netroy** [comment]
@geoidesic can you please share more info on where this code is running, what runtime, what version of the runtime, etc. 
without being able to reproduce it, I wouldn't know what to fix.

**Comment by geoidesic** [comment]
Sure.. this is running in a Sveltekit component. 
Node v16.2.0
Yarn 1.22.10

**Comment by geoidesic** [comment]
It could be a vite error... I know next to nothing about Vite.

**Comment by netroy** [comment]
![Screenshot-20210804-100915](https://user-images.githubusercontent.com/196144/128145951-38793c6c-8c96-40a1-a7d8-336d9e29efdc.png)
`exports.default` is very clearly defined. this is most definitely an issue with Vite.

I'm not familiar with Vite, and it's unlikely that I'll have enough time anytime soon to learn enough about Vite to fix this issue, I'm gonna close this issue. 
If someone more familiar with Vite wants to send a pr, I'd be more than happy to help and review.
