### ISSUE TITLE
Fails on SVG assets without `width` and `height` properties

### ISSUE THREAD

**Issue by kyleolsondesign** [image-size/image-size#38]
Using a tool like Adobe Illustrator to create SVG assets, you get output that does not include `width` or `height` properties. Here is a sample of that output, after being compressed with [imagemin](https://github.com/imagemin/imagemin):

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-15.6 130.7 612 507" enable-background="new -15.6 130.7 612 507"></svg>
```

Running through the w3c validator, this is valid SVG 1.1.

But when I run through `sizeOf`, I get the following error:
> Uncaught TypeError: invalid svg

If I manually add the `width` and `height` attributes, `sizeOf` works as expected:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="612" height="507" viewBox="-15.6 130.7 612 507" enable-background="new -15.6 130.7 612 507"></svg>
```

The `width` and `height` attributes are described in the [`viewBox`](http://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute) attribute already, as the last two values. I suggest pulling from those values if the `width` and `height` attributes are not present.

**Comment by borodean** [comment]
@kyleolsondesign would be fixed when https://github.com/netroy/image-size/pull/36 is merged.

**Comment by mdmoreau** [comment]
Any updates on this?  Would be great to get it added in.

**Comment by rlee1121** [comment]
+1

**Comment by tiroxis** [comment]
+1

**Comment by shinnn** [comment]
#36 is merged.
