### ISSUE TITLE
Consider using static require dependencies

### ISSUE THREAD

**Issue by whitecolor** [image-size/image-size#39]
There is an issue when using the package with https://github.com/jspm (sytemjs)
https://github.com/jspm/registry/issues/221

this code uses dynamic requires
https://github.com/netroy/image-size/blob/master/lib/index.js#L6-L15

and https://github.com/systemjs/systemjs can not handle it.

Actually it is importaint as `image-size` is used with css precompilers (such as LESS) and they have to be used in systemjs-builder worflow.

Would you consider chanding requires to static paths? Or addings static `deps` declarations in the beginning of the file?

**Comment by pawlufelice** [comment]
This is a problem for me too!! I have browserify on an express app and the dynamic requires just to not get bundled, resulting in `module not found`. Please have them changed to static. Thanks

**Comment by danielweck** [comment]
Indeed, Browserify (which ; by the way ; is not only used for client-side bundling, but can also be used to package server-side code, e.g. in Electron) fails to fulfill the dynamic `require()` calls, for instance:
https://github.com/image-size/image-size/blob/a71d6372c95e79efa0b349153a8525381aab0e5c/lib/index.js#L9-L14
(from the `types` list defined at https://github.com/image-size/image-size/blob/master/lib/types.js )

The current workaround is to add another `file.js` in my source tree, where I explictly `require` each "type" using a hard-coded path. This is actually standard practice in several CommonJS libs, to ensure Browserify (and others) compatibility.

**Comment by eiwi1101** [comment]
@danielweck Thanks for the fork! The dynamic requires are a little too much magic for Browserify et. al. 

Do you have an open PR for your fork to start that discussion with the maintainers?

**Comment by danielweck** [comment]
My fork currently contains a quick-and-dirty patch, not a PR-ready contribution. My naive fix effectively makes the hard-coded list of types ( https://github.com/image-size/image-size/blob/master/lib/types.js ) useless. A clean fix would probably (at least) check that this list is consistent with the non-dynamic requires, or remove the list altogether.

**Comment by eiwi1101** [comment]
Yeah, after my comment I took a peek at the open PRs on the main repo and found #98, which seems to be a pretty solid fix. Last activity there was September, Here's hoping it goes in soon-ish.

**Comment by danielweck** [comment]
Oh great, thank for spotting this :)

**Comment by netroy** [comment]
fixed in #105 & released as `0.6.2`
