### ISSUE TITLE
Skip garbge bytes in jpg

### ISSUE THREAD

**Issue by xiaozhuai** [image-size/image-size#392]
Hello @netroy 
My project https://github.com/xiaozhuai/imageinfo use many test image files from your repo. Thanks again!
And there is a bug report about jpg. See https://github.com/xiaozhuai/imageinfo/issues/4

And I found that image-size has the same problem.
```
Invalid JPG, marker table corrupted - /Users/xiaozhuai/work/imageinfo/images/valid/jpg/sample2.jpg
```

Just remind you.

Best wishes : )

**Comment by netroy** [comment]
Thanks for letting me know. 
[I've updated the code to skip the byte instead of throwing an explicit error](https://github.com/image-size/image-size/pull/393). 
Hopefully this doesn't start producing results for completely garbled JPEGs 🤞🏽 😅
