### ISSUE TITLE
Support bigtiff

### ISSUE THREAD

**Issue by xiaozhuai** [image-size/image-size#415]
Hello @netroy 
I recently received an issue about bigtiff, see https://github.com/xiaozhuai/imageinfo-rs/issues/5 for details.
Then I checked image-size and found that bigtiff is not supported either.
```
$ image-size BigTIFF*
unsupported file type: undefined (file: BigTIFF.tif) - BigTIFF.tif
unsupported file type: undefined (file: BigTIFFLong.tif) - BigTIFFLong.tif
unsupported file type: undefined (file: BigTIFFMotorola.tif) - BigTIFFMotorola.tif
```
Test image files can be found in https://github.com/xiaozhuai/imageinfo-rs/tree/master/images/valid/tiff.

Just remind you.
Best wishes : )

**Comment by netroy** [comment]
Thanks for letting me know 😊
