### ISSUE TITLE
Support JFIF extension (JFXX) segment format

### ISSUE THREAD

**Issue by sixmen** [image-size/image-size#44]
Format: http://en.wikipedia.org/wiki/JPEG_File_Interchange_Format#JFIF_extension_.28JFXX.29_segment_format

Example file: http://www.ofvalue.co.kr/web/product/medium/201503/969_shop1_197963.jpg

**Comment by shinnn** [comment]
Fixed in https://github.com/image-size/image-size/pull/50.
