### ISSUE TITLE
Use in browser context

### ISSUE THREAD

**Issue by aleemb** [image-size/image-size#51]
Would be nice to use this in the browser context, which right now fails due to `fs` requirement not being met in the browser.

I am trying to use it with webpack. I could use `image.onload` but that loads the entire image versus just sniffing the image headers from the first couple of bytes without loading the entire image.

**Comment by shinnn** [comment]
Duplicate of https://github.com/image-size/image-size/issues/20. On browser you can use `window.Image` instead.
