### ISSUE TITLE
Transfering the ownership of this project

### ISSUE THREAD

**Issue by netroy** [image-size/image-size#58]
Unfortunately, I don't have the time or the energy to participate in this project anymore, so I'm looking for people who'd like to take over this project. 
I've already moved the project to an independent organisation & added some previous contributors to this organisation.

I've also added @zeke as an owner on github, as well as on npm.

My deepest apologies for not being available for a long time; Didn't expect this repo to get so much traction.

//cc @shinnn @LinusU @borodean

**Comment by LinusU** [comment]
I would love to help out! I'm `linusu` on npm.

**Comment by borodean** [comment]
Sorry, I've already switched to using [calipers](https://github.com/lob/calipers) and contributing to it.

However, I'd love to help to merge https://github.com/image-size/image-size/pull/36 because of my legacy customers.

**Comment by zeke** [comment]
Thanks for the update, @netroy. It looks like @shinnn is already doing an awesome job cleaning house. :)

**Comment by shinnn** [comment]
Wow, nice organization icon! https://github.com/image-size Who did it?

**Comment by zeke** [comment]
twas me :)

**Comment by shinnn** [comment]
@zeke :clap:

**Comment by borodean** [comment]
:+1:
