### ISSUE TITLE
support promises

### ISSUE THREAD

**Issue by aeosynth** [image-size/image-size#61]
i'd like to use this asynchronously with promises, instead of the nodejs style callback. currently i'm manually promisifying the async version.

**Comment by Kikobeats** [comment]
unnecessary at node 8:

```
const promisify = require('util')
const sizeOf = promisify(require('image-size')),
```

**Comment by AMorgaut** [comment]
well

first I think that it would at least worth an update in the readme to be more user-friendly

then, an helper such as 

```javascript
const { sizeOf } = require('image-size');
```

returning a promisified version of the function

It would not cost nor break anything

I can volunteer to push this micro feature

**Comment by netroy** [comment]
I added usage with [promises](https://github.com/image-size/image-size#using-promises-node-8x) & [async/await](https://github.com/image-size/image-size#asyncawait-typescript--es7) in the readme now

**Comment by AMorgaut** [comment]
Just Cosmetic Notes ;-)

```javascript
  .then(dimensions => { console.log(dimensions.width, dimensions.height); })
```

* the curly brackets are not mandatory for one only instruction
* might have use destructuring as well

ex:
```javascript
  .then(({ width, height }) => console.log(width, height))
```

destructuring could also be used in the Async example

```javascript
  const { width, height } = await sizeOf('images/funny-cats.png');
  console.log(width, height);
```
