### ISSUE TITLE
browser support (again)

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [image-size/image-size#62]
Hello,

Sorry to ask again for browser support but the solution you suggested (`new Image ...`) does not work in web workers. 

There are libraries compatibles such as png.js and jpg.js but I could not find a way to get the size of a picture.

Best,

Guillaume Leclerc

**Comment by micky2be** [comment]
I would love browser support too please.
I'm dealing with buffers on the frontend.
The only thing stopping me from using this module here is the 'fs' dependency.

**Comment by jeremymlane** [comment]
See: https://github.com/finalweb/image-worker

**Comment by awerlang** [comment]
With rollup, it's possible to mock node modules likes this:

rollup-config.js
```js
plugins: [
    { resolveId(a,b) { return a === 'fs' && './empty.js' || null } },
    { resolveId(a,b) { return a === 'path' && './empty.js' || null } },
    ...
```

empty.js
```js
export default {};
```

The problem then is #39

**Comment by netroy** [comment]
#39 is fixed. 
I'd recommend using [@awerlang 's solution](https://github.com/image-size/image-size/issues/62#issuecomment-314295908) for browser support.
