### ISSUE TITLE
No support for webp VP8X format

### ISSUE THREAD

**Issue by Coobers** [image-size/image-size#65]
Webp files in extended format will return false in method calculate in lib/types/webp.js.
It's chunkHeader is VP8X.
Details: https://developers.google.com/speed/webp/docs/riff_container#extended_file_format

This is quite severe since all 3 webp formats are interchangeable and parsing properly in browsers.

**Comment by shinnn** [comment]
PR welcome.

**Comment by nullne** [comment]
Yes, I met this problem too. do you @Coobers  have any solutions ?

**Comment by Coobers** [comment]
Can you send me your vp8x image file?
I can try to recreate fix, but I have no test images with me at the moment ;)

**Comment by nullne** [comment]
I cannot upload that file here which is not supported by GitHub.
This is the original link of that image: http://res.cloudinary.com/demo/image/upload/fl_awebp/bored_animation.webp

**Comment by Coobers** [comment]
This is procedure we used in company to "overcome" this bug.
Note that I did not fixed lack of size, just get around it (line in code might not correspond now):

> Modify webp library ./node_modules/react-native/node_modules/image-size/lib/types/webp.js line 19 to:
> 
> (chunkHeader === 'VP8 ' || chunkHeader === 'VP8X')
> 
> Without it, during compiling you might receive error: uncaught error Error: TypeError: unsupported file type
> 
> it's due to error in image-size lib which do not include WEBPX format: https://github.com/image-size/image-size/issues/65
> 
> Clean the project afterwards.

**Comment by netroy** [comment]
@Coobers @nullne released as 0.5.1
