### ISSUE TITLE
Url becomes Local path

### ISSUE THREAD

**Issue by wahengchang** [image-size/image-size#68]
I have got problem that given a URL of an image, but the url turns to local path in sizeOf( )

============================================
==================     my code     ===============
============================================
	var imgUrl = 'https://abe/photo.jpg';
	sizeOf(imgUrl, function(err, dimensions, length) {
	  console.log(err, dimensions, length);
	});

============================================
=================      Error Msg      ==============
============================================

GET /2 200 22.530 ms - 210
{ [Error: ENOENT: no such file or directory, open '/Users/abc/Desktop/node/image_size/https://abe/photo.jpg']

============================================

**Comment by shinnn** [comment]
That's an expected behavior. The first argument doesn't accept URL.

**Comment by wahengchang** [comment]
hey shinnn , thanks for you reply,  is there a way that I can check the size of image from URL

**Comment by shinnn** [comment]
https://github.com/image-size/image-size/tree/e67273e812682b4aa8679bd3cd58a037c9a60833#using-a-url
