### ISSUE TITLE
Adding quotes around Height and Width values

### ISSUE THREAD

**Issue by Ayysir** [image-size/image-size#72]
Im developing an android application and Json parser class i am using will not see values because they are not put into quotation marks

**Comment by zeke** [comment]
If you need your values to be strings, just cast them to strings:

```js
String(123)
'123'
```

**Comment by Ayysir** [comment]
@zeke 
this is how i am doing it

`var sizeOf = require('image-size');
      var dimensions = sizeOf(fileDir + fileName);`

filedir and filename are already defined variable. cow can i cast it in that code?

**Comment by Ayysir** [comment]
I cant cant cast height and width values to strings....

**Comment by zeke** [comment]
```js
var dimensions = {width: 123, height: 456}
dimensions.width = String(dimensions.width)
dimensions.height = String(dimensions.height)
JSON.stringify(dimensions)
```

**Comment by Ayysir** [comment]
@zeke  thank you very much, sorry to be PITA lol. Learned something new today

**Comment by zeke** [comment]
No problem @Ayysir!
