### ISSUE TITLE
example request

### ISSUE THREAD

**Issue by TrejGun** [image-size/image-size#75]
Please add an example of how to check size of image uploaded via express.js

**Comment by shinnn** [comment]
http://stackoverflow.com is the better place for this kind of requests.

**Comment by TrejGun** [comment]
@shinnn really?
this lib is not so popular to be even mentioned on SO
and won't be unless it has examples of how to use it with frameworks
so please add it

**Comment by shinnn** [comment]
You don't need to care about the popularity of this project.

**Comment by TrejGun** [comment]
@shinnn oh i'm so sorry that opensource community is bugging you - do this, do that. may be its better to make project private so nobody will bother you.

**Comment by zeke** [comment]
This issue is going off the rails, so I'm going to lock it down.
