### ISSUE TITLE
iPhone picture rotation

### ISSUE THREAD

**Issue by jonaswindey** [image-size/image-size#76]
When detecting the size of an iPhone (6) image, it always returns 3264 x 2448, even when it's a portrait image.

It should understand the orient information from the Exif data.

**Comment by puzrin** [comment]
That should be some kind of option (or result daya), because depends on orientation flag, responsible for representation. If you need real value for resize, coords swap will be a problem.

**Comment by mhulse** [comment]
Not sure if it is of help, but I use [`jhead`](http://www.sentex.net/~mwandel/jhead/) to fix orientation before processing:

```bash
$ cd files/imagesfolder/
$ jhead -autorot -q -se files/downloads/*.{jpg,JPG,jpeg,JPEG} 2> /dev/null
```

**Comment by artscoop** [comment]
Unfortunately, `jhead` is not lossless. It is currently trimming a side of a picture I'm unit-testing.

**Comment by paulcowles** [comment]
The library does return orientation code for jpegs. You can use it to flip height/width [if necessary](https://github.com/recurser/exif-orientation-examples). Yes, it would be nice if this was automatically done, but you can do it in the callback.

**Comment by netroy** [comment]
orientation support was added in `0.7.1` (Jan 2019), but I forgot to update this ticket.
Here is the commit that landed the change https://github.com/image-size/image-size/commit/93cb70f09c143542085297af52e7ebf9d9177fd8

based on the raw orientation value, it should be possible to swap the width & height values.
swapping the values in this library will make it backward in-compatible (unfortunately).
