### ISSUE TITLE
Support for .ico

### ISSUE THREAD

**Issue by vteremasov** [image-size/image-size#82]
As long as [webpack-favicon-plugin](https://www.npmjs.com/package/favicons-webpack-plugin) uses image-size could you add support for `.ico` format?

Now when I try to run with favicon.ico get 
`node_modules/image-size/lib/index.js:34
  throw new TypeError('unsupported file type');
`

**Comment by LinusU** [comment]
That would be very nice, PR welcome 🙌

**Comment by puzrin** [comment]
@vteremasov what output do you expect if icon contains multiple sizes?

**Comment by vteremasov** [comment]
@puzrin Agree, issue should be solved somehow else

**Comment by AMorgaut** [comment]
I wrote a first implementation on my fork

> https://github.com/AMorgaut/image-size/tree/issues/82/support-for-.ico

I expect to send a pull-request once I'll have added few tests to get full coverage

Any feedback on the implementation choices is welcome before I send it

The @puzrin question is very valid as depending of the situation, the user might expect to get either:

* the dimensions of the first image
* the dimensions of the last image
* the dimensions of the smallest image
* the dimensions of the biggest image

Here the status:

* It handles `.cur` & `.ico` files (they have the same structure)
* It returns the `width` & the `height` of the **first image** of the file
* It adds an extra `images` array property with **the width & height of all the images of the file**

**Comment by AMorgaut** [comment]
I just created the promised pull-request
I added cli support for the multi-size images

**Comment by AMorgaut** [comment]
The pull request has been merged and the feature has been published on npm 

I think the issue can now be closed ;-)
