### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by TinlerLin** [image-size/image-size#92]
open a normal jpg image, got the error "Invalid JPG, marker table corrupted"

**Comment by shinnn** [comment]
That's an expected behavior. https://github.com/image-size/image-size/blob/86691cf1d19ca4ac0716bb3579f7667bbac97532/lib/types/jpg.js#L25-L28

**Comment by TinlerLin** [comment]
Thanks for your replay.

At 2017-07-06 14:19:53, "Shinnosuke Watanabe" <notifications@github.com> wrote:


That's an expected behavior. https://github.com/image-size/image-size/blob/86691cf1d19ca4ac0716bb3579f7667bbac97532/lib/types/jpg.js#L25-L28
