### ISSUE TITLE
Asynchronous version is not fully asynchronous

### ISSUE THREAD

**Issue by mrkvon** [image-size/image-size#99]
When running async version of this library in node v4.0+ with `--trace-sync-io` we get `WARNING: Detected use of sync API`.

Specifically `fs.fstatSync` in [./lib/index.js#L41](/image-size/image-size/blob/master/lib/index.js#L41)

If running on production server, it might lead to reduced performance.
May be trivial to replace with the asynchronous version `fs.fstat`?

**Comment by LinusU** [comment]
Seems to me like it would be even better to just skip the stat-call altogether, and just look at the return value from the read-call...
